name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - setuptools==69.5.1
  - python=3.8
  - pip=24.0
  # pip install torch==2.1.0 torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cu121
  - pytorch=2.1.0
  - torchvision=0.16.0
  - tqdm
  - torchmetrics[image]
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
